// src/components/docs/version-switcher.tsx


import { useState } from "react"
import { Check, ChevronDown } from "lucide-react"
import { useRouter } from "next/navigation"

interface VersionSwitcherProps {
  currentVersion: string
  versions: string[]
}

export function VersionSwitcher({ currentVersion, versions }: VersionSwitcherProps) {
  const [open, setOpen] = useState(false)
  const router = useRouter()

  const handleVersionChange = (version: string) => {
    router.push(`/docs/${version}`)
    setOpen(false)
  }

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-2 px-3 py-2 text-sm text-foreground bg-muted rounded-md hover:bg-muted/80 transition-colors"
      >
        <span className="font-medium">{currentVersion}</span>
        <ChevronDown className="h-4 w-4" />
      </button>

      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className="absolute right-0 mt-2 w-48 bg-background border border-border rounded-md shadow-lg z-50">
            <div className="p-2">
              {versions.map((version) => (
                <button
                  key={version}
                  onClick={() => handleVersionChange(version)}
                  className="flex items-center justify-between w-full px-3 py-2 text-sm text-foreground hover:bg-muted rounded-md transition-colors"
                >
                  <span>{version}</span>
                  {version === currentVersion && <Check className="h-4 w-4 text-primary" />}
                </button>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  )
}

// src/lib/components/docs/VersionSwitcher.svelte
<script lang="ts">
  import { ChevronDown, Check } from 'lucide-svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { browser } from '$app/environment';

  interface Props {
    currentVersion: string;
    versions: string[];
  }

  let { currentVersion, versions }: Props = $props();

  let isOpen = $state(false);
  let dropdownEl = $state<HTMLDivElement | null>(null);

  $effect(() => {
    if (!browser || !isOpen) return;

    function handleClickOutside(e: MouseEvent) {
      if (dropdownEl && !dropdownEl.contains(e.target as Node)) {
        isOpen = false;
      }
    }

    function handleEscape(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        isOpen = false;
      }
    }

    document.addEventListener('click', handleClickOutside);
    document.addEventListener('keydown', handleEscape);

    return () => {
      document.removeEventListener('click', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
    };
  });

  function switchVersion(version: string) {
    if (version === currentVersion) {
      isOpen = false;
      return;
    }

    const currentPath = $page.url.pathname;
    const newPath = currentPath.replace(
      new RegExp(`/${currentVersion}(/|$)`),
      `/${version}$1`
    );

    isOpen = false;
    goto(newPath);
  }
</script>

{#if versions.length > 1}
  <div class="relative" bind:this={dropdownEl}>
    <button
      onclick={() => (isOpen = !isOpen)}
      class="flex items-center gap-1.5 h-8 px-3 text-sm font-medium rounded-md border border-border bg-background hover:bg-accent transition-colors text-foreground"
      aria-expanded={isOpen}
      aria-haspopup="listbox"
      aria-label="Switch version"
    >
      <span>{currentVersion}</span>
      <ChevronDown class="h-3.5 w-3.5 text-muted-foreground transition-transform {isOpen ? 'rotate-180' : ''}" />
    </button>

    {#if isOpen}
      <div
        class="absolute top-full right-0 mt-1 w-40 py-1 bg-popover border border-border rounded-md shadow-lg z-50"
        role="listbox"
        aria-label="Available versions"
      >
        {#each versions as version}
          <button
            role="option"
            aria-selected={version === currentVersion}
            onclick={() => switchVersion(version)}
            class="w-full flex items-center justify-between px-3 py-1.5 text-sm transition-colors {version === currentVersion
              ? 'text-primary bg-accent/50 font-medium'
              : 'text-foreground hover:bg-accent'}"
          >
            <span>{version}</span>
            {#if version === currentVersion}
              <Check class="h-3.5 w-3.5 text-primary" />
            {/if}
          </button>
        {/each}
      </div>
    {/if}
  </div>
{/if}
