// src/components/docs/api/api-params.tsx
export interface ApiParam {
  name: string
  type: string
  required?: boolean
  description?: string
  default?: string
}

export interface ApiParamsProps {
  title?: string
  params: ApiParam[]
}

export function ApiParams({ title = "Parameters", params }: ApiParamsProps) {
  if (!params || params.length === 0) return null

  return (
    <div className="mb-6">
      <h4 className="text-sm font-semibold text-foreground mb-3">{title}</h4>
      <div className="overflow-x-auto">
        <table className="w-full border-collapse">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Property
              </th>
              <th className="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Type
              </th>
              <th className="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Required
              </th>
              <th className="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Default
              </th>
              <th className="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Description
              </th>
            </tr>
          </thead>
          <tbody>
            {params.map((param, index) => (
              <tr
                key={param.name}
                className={index !== params.length - 1 ? "border-b border-border/50" : ""}
              >
                <td className="py-2.5 px-3">
                  <code className="text-sm font-mono text-foreground">{param.name}</code>
                </td>
                <td className="py-2.5 px-3">
                  <span className="text-sm text-muted-foreground font-mono">{param.type}</span>
                </td>
                <td className="py-2.5 px-3">
                  {param.required ? (
                    <span className="text-sm text-red-600 dark:text-red-400">Yes</span>
                  ) : (
                    <span className="text-sm text-muted-foreground">No</span>
                  )}
                </td>
                <td className="py-2.5 px-3">
                  {param.default ? (
                    <code className="text-sm font-mono text-muted-foreground">{param.default}</code>
                  ) : (
                    <span className="text-sm text-muted-foreground">-</span>
                  )}
                </td>
                <td className="py-2.5 px-3">
                  {param.description ? (
                    <span className="text-sm text-muted-foreground">{param.description}</span>
                  ) : (
                    <span className="text-sm text-muted-foreground">-</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// src/lib/components/docs/api/ApiParams.svelte
<script lang="ts">
  export interface ApiParam {
    name: string;
    type: string;
    required?: boolean;
    description?: string;
    default?: string;
  }

  interface Props {
    title?: string;
    params: ApiParam[];
  }

  let { title = 'Parameters', params }: Props = $props();
</script>

{#if params && params.length > 0}
  <div class="mb-6">
    <h4 class="text-sm font-semibold text-foreground mb-3">{title}</h4>
    <div class="overflow-x-auto">
      <table class="w-full border-collapse">
        <thead>
          <tr class="border-b border-border">
            <th class="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Property
            </th>
            <th class="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Type
            </th>
            <th class="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Required
            </th>
            <th class="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Default
            </th>
            <th class="text-left py-2 px-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Description
            </th>
          </tr>
        </thead>
        <tbody>
          {#each params as param, index}
            <tr
              class={index !== params.length - 1 ? 'border-b border-border/50' : ''}
            >
              <td class="py-2.5 px-3">
                <code class="text-sm font-mono text-foreground">{param.name}</code>
              </td>
              <td class="py-2.5 px-3">
                <span class="text-sm text-muted-foreground font-mono">{param.type}</span>
              </td>
              <td class="py-2.5 px-3">
                {#if param.required}
                  <span class="text-sm text-red-600 dark:text-red-400">Yes</span>
                {:else}
                  <span class="text-sm text-muted-foreground">No</span>
                {/if}
              </td>
              <td class="py-2.5 px-3">
                {#if param.default}
                  <code class="text-sm font-mono text-muted-foreground">{param.default}</code>
                {:else}
                  <span class="text-sm text-muted-foreground">-</span>
                {/if}
              </td>
              <td class="py-2.5 px-3">
                {#if param.description}
                  <span class="text-sm text-muted-foreground">{param.description}</span>
                {:else}
                  <span class="text-sm text-muted-foreground">-</span>
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  </div>
{/if}
